<h3 align='center'>Programacion</h3>
<h3 align='center'>Jorge Andres Duque Restrepo</h3>
<h3 align='center'>Mini challenge #7</h3>
<h3 align='center'>28/04/2023</h3>

In [3]:
import numpy as np

#### Escriba un programa para generar un vector de $N$ números aleatorios a partir de una distribución normal estándar, usando una precisión de dos cifras decimales. Luego, estos números se deben poner sobre la diagonal de una matriz $N \times N$, cuyos elementos por fuera de esta son todos cero.

In [ ]:
#pido e inicializo las variables necesarias para poder realizar mi ejercicio
np.random.seed(0)
N = int(input('ingrese que tamaño quiere que sea el vector'))
A = np.random.random(N)
Z = np.zeros((N,N))
aux=0
#modifico mi arreglo para qeu sus datos queden de dos cifras decimales
A = np.round(A,decimals=2)

#cicflo for para meter mi arreglo en la matriz
for idx in Z:
    idx[aux]=A[aux]
    aux+=1
print(f"Arreglo aleatorio\n{A}\n")
print(f"Matriz de zeros\n{Z}")


#### Escriba un programa para crear una matriz de $10\times 10$, en la que los elementos en los bordes sean iguales a un número especificado por el usuario y los interiores iguales a 0.

In [8]:
#pido al usuario el valor que quiere meter dentro de la matriz y la inicializo
N_2 = int(input('ingrese el numero que quiere ver dentro de la matriz'))
Z_2 = np.zeros((10,10))
A_2 = np.random.randint(N_2,N_2+1, size=10)

#modifico la primera/ultima fila y columna de mi matriz
Z_2[:,0]=A_2
Z_2[:,9]=A_2
Z_2[0,:]=A_2
Z_2[9,:]=A_2

print(Z_2)

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]
