Primero, hice una tabla con distintos modelos de los componentes de mi proyecto para asi hacer varias rutas y ver cual de todas es la mejor en terminos de facilidad y economia. Apoyandome de ChatGPT, claro esta.

In [24]:
import numpy as np
import csv

In [9]:
flood_fill = np.zeros((5,5,5))
aux_unos = 1.0
x = 1

#delimito las fronteras de mi laberinto
for idx in range(0,5,1):
    flood_fill[1][idx][4]=aux_unos
    flood_fill[3][idx][0]=aux_unos
    flood_fill[2][0]=aux_unos
    flood_fill[4][4]=aux_unos

#Configuro las paredes de adentro de mi laberinto
for idx in range(0,5,1):
    flood_fill[1][idx][4]=aux_unos
    flood_fill[3][idx][0]=aux_unos

for idx in range(0,5,1):
    flood_fill[2][0]=aux_unos
    flood_fill[4][4]=aux_unos

while x == 1:
    matriz = int(input("ingrese la matriz a editar"))
    fila = int(input("ingrese que fila de dicha matriz quiere editar"))
    columna = int(input("ingrese la columna de dicha matriz quiere editar"))
    
    flood_fill[matriz][fila][columna] = 1

    x = int(input("1 para seguir agregando muros, 0 para terminar"))

print(flood_fill[1:])

[[[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[1. 0. 0. 1. 0.]
  [1. 0. 1. 0. 1.]
  [1. 1. 1. 0. 0.]
  [1. 1. 0. 0. 1.]
  [1. 1. 0. 0. 0.]]

 [[1. 0. 0. 1. 0.]
  [0. 1. 1. 0. 0.]
  [0. 0. 1. 1. 0.]
  [0. 0. 1. 1. 0.]
  [1. 1. 1. 1. 1.]]]


In [23]:
x = np.random.random((2,3))
y = np.arange(3)

print(y)
print(x)

x[0]=y

print(x)

[0 1 2]
[[0.81461714 0.5814532  0.09633817]
 [0.7296421  0.58893934 0.2261124 ]]
[[0.         1.         2.        ]
 [0.7296421  0.58893934 0.2261124 ]]
