Primero, hice una tabla con distintos modelos de los componentes de mi proyecto para asi hacer varias rutas y ver cual de todas es la mejor en terminos de facilidad y economia. Apoyandome de ChatGPT, claro esta.

In [2]:
import numpy as np

In [36]:
flood_fill = np.zeros((4,5,5))

for idx in range(0,5,1):
    flood_fill[0][4][idx]=idx
print(flood_fill[0])
print(flood_fill[0][4][4])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]]
4.0
