Primero, hice una tabla con distintos modelos de los componentes de mi proyecto para asi hacer varias rutas y ver cual de todas es la mejor en terminos de facilidad y economia. Apoyandome de ChatGPT, claro esta.

In [1]:
import numpy as np
import csv

In [1]:
flood_fill = np.zeros((5,5,5))
aux_unos = 1.0
x = 1

#delimito las paredes de mi laberinto y los valores de cada celda
with open('archivos_csv/posiciones.csv','r') as csv_file:
    flood_fill[0] = np.loadtxt(csv_file,delimiter=";")
with open('archivos_csv/este.csv','r') as csv_file2:
    flood_fill[1] = np.loadtxt(csv_file2,delimiter=";")
with open('archivo_csv/norte.csv','r') as csv_file3:
    flood_fill[2] = np.loadtxt(csv_file3,";")
with open('archuvo_csv/oeste.csv','r') as csv_file4:
    flood_fill[3] = np.loadtxt(csv_file4,delimiter=";")
with open('archivo_csv/sur.csv','r') as csv_file5:
    flood_fill[4] = np.loadtxt(csv_file5,delimiter=";")

print(flood_fill[1:])

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "c:\Users\Acer\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Acer\AppData\Local\Temp\ipykernel_12516\3715526757.py", line 1, in <module>
    flood_fill = np.zeros((5,5,5))
NameError: name 'np' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Acer\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2077, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Acer\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "c:\Users\Acer\anaco

TypeError: object of type 'NoneType' has no len()

In [2]:

flood_fill = np.zeros((5,5,5))
with open('archivos_csv/posiciones.csv','r') as csv_file:
    csv_reader = np.loadtxt(csv_file,delimiter=";")
    print(csv_reader)

[[ 6.  5.  4.  5.  4.]
 [ 7.  6.  3.  2.  3.]
 [ 8.  9.  0.  1.  2.]
 [ 9.  8.  9. 10.  3.]
 [10.  7.  6.  5.  4.]]
