Primero, hice una tabla con distintos modelos de los componentes de mi proyecto para asi hacer varias rutas y ver cual de todas es la mejor en terminos de facilidad y economia. Apoyandome de ChatGPT, claro esta.

In [3]:
import numpy as np
import csv

In [7]:
flood_fill = np.zeros((5,5,5))
aux_unos = 1.0
x = 1

#delimito las paredes de mi laberinto y los valores de cada celda
with open('archivos_csv/posiciones.csv','r') as csv_file:
    flood_fill[0] = np.loadtxt(csv_file,delimiter=";")
with open('archivos_csv/este.csv','r') as csv_file2:
    flood_fill[1] = np.loadtxt(csv_file2,delimiter=";")
with open('archivos_csv/norte.csv','r') as csv_file3:
    flood_fill[2] = np.loadtxt(csv_file3,delimiter=";")
with open('archivos_csv/oeste.csv','r') as csv_file4:
    flood_fill[3] = np.loadtxt(csv_file4,delimiter=";")
with open('archivos_csv/sur.csv','r') as csv_file5:
    flood_fill[4] = np.loadtxt(csv_file5,delimiter=";")

print(flood_fill[0])
print(flood_fill[1:])

[[ 6.  5.  4.  5.  4.]
 [ 7.  6.  3.  2.  3.]
 [ 8.  9.  0.  1.  2.]
 [ 9.  8.  9. 10.  3.]
 [10.  7.  6.  5.  4.]]
[[[0. 0. 1. 0. 1.]
  [0. 1. 0. 1. 1.]
  [1. 1. 0. 0. 1.]
  [1. 0. 0. 1. 1.]
  [1. 0. 0. 0. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 0. 0. 1. 0.]
  [0. 1. 1. 0. 0.]
  [0. 0. 1. 1. 0.]
  [0. 0. 1. 1. 0.]]

 [[1. 0. 0. 1. 0.]
  [1. 0. 1. 0. 1.]
  [1. 1. 1. 0. 0.]
  [1. 1. 0. 0. 1.]
  [1. 1. 0. 0. 0.]]

 [[1. 0. 0. 1. 0.]
  [0. 1. 1. 0. 0.]
  [0. 0. 1. 1. 0.]
  [0. 0. 1. 1. 0.]
  [1. 1. 1. 1. 1.]]]


In [2]:

flood_fill = np.zeros((5,5,5))
with open('archivos_csv/posiciones.csv','r') as csv_file:
    csv_reader = np.loadtxt(csv_file,delimiter=";")
    print(csv_reader)

[[ 6.  5.  4.  5.  4.]
 [ 7.  6.  3.  2.  3.]
 [ 8.  9.  0.  1.  2.]
 [ 9.  8.  9. 10.  3.]
 [10.  7.  6.  5.  4.]]
