Primero, hice una tabla con distintos modelos de los componentes de mi proyecto para asi hacer varias rutas y ver cual de todas es la mejor en terminos de facilidad y economia. Apoyandome de ChatGPT, claro esta.

In [1]:
import numpy as np
import csv

In [33]:
flood_fill = np.zeros((5,5,5))
aux_u=0
aux_uf=0.0
aux_uc=0.0

#delimito las paredes de mi laberinto y los valores de cada celda
with open('archivos_csv/posiciones.csv','r') as csv_file:
    flood_fill[0] = np.loadtxt(csv_file,delimiter=";")
with open('archivos_csv/este.csv','r') as csv_file2:
    flood_fill[1] = np.loadtxt(csv_file2,delimiter=";")
with open('archivos_csv/norte.csv','r') as csv_file3:
    flood_fill[2] = np.loadtxt(csv_file3,delimiter=";")
with open('archivos_csv/oeste.csv','r') as csv_file4:
    flood_fill[3] = np.loadtxt(csv_file4,delimiter=";")
with open('archivos_csv/sur.csv','r') as csv_file5:
    flood_fill[4] = np.loadtxt(csv_file5,delimiter=";")

#inicializo el vector en el que el robot sabra su ubicacion y arreglo en el que se guardara la ubicacion proxima
aux_u = input("ingresar ubicacion, primero fila luego columna separando por una coma").split(sep=",")
ubicacion = np.array([int(x) for x in aux_u])

decicion = np.empty_like(ubicacion)

print (ubicacion[0]+1 == 5 ^ True)

#while flood_fill[0][ubicacion[0]][ubicacion[1]] != 0:
    #Creo el codigo de toma de deciciones de mi robor
    #todas las direcciones  
if ubicacion[0]-1  > 0 and ubicacion[1]-1 > 0 and ubicacion[0]+1  < 5 and ubicacion[1]+1 < 5:
    print("hola")
    #avanza hacia el este 
    if (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]+1] and flood_fill[1][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[1]+=1

    #avanza hacia el norte 
    elif (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]-1][ubicacion[1]] and flood_fill[2][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[0]-=1
    
    #avanza hacia el oeste 
    elif (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]-1] and flood_fill[3][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[1]-=1

    #avanza hacia el sur
    elif (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]+1][ubicacion[1]] and flood_fill[4][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[0]+=1

#fila superior
elif ubicacion[0]-1 == -1 ^ (ubicacion[1]-1 == -1 or ubicacion[1]+1 == 5):
    #Avanza hacia el este
    if ubicacion[0]-1 == -1 and (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]+1] and flood_fill[1][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[1]+=1

    #Avanza hacia el oeste
    elif ubicacion[0]-1 == -1 and (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]-1] and flood_fill[3][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[1]-=1

    #Avanza hacia el sur 
    elif ubicacion[0]-1 == -1 and (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]+1][ubicacion[1]] and flood_fill[4][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[0]+=1

#Fila inferior 
elif ubicacion[0]+1 == 5 ^ (ubicacion[1]-1 == -1 or ubicacion[1]+1 == 5):
    #Avanza hacia el este
    if ubicacion[0]+1 == 5 and (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]+1] and flood_fill[1][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[1]+=1

    #Avanza hacia el norte 
    elif ubicacion[0]+1 == 5 and (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]-1][ubicacion[1]] and flood_fill[2][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[0]-=1

    #Avanza hacia el oeste  
    elif ubicacion[0]+1 == 5 and (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]-1] and flood_fill[3][ubicacion[0]][ubicacion[1]] != 1:
        ubicacion[1]-=1

#Columna izquierda
elif ubicacion[1]-1 == -1:
    #fuera de las esquinas
    if ubicacion[0]-1 >= 0 and ubicacion[0]+1 <= 4:
        print("hola")
        #Avanza hacia el este
        if (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]+1] and flood_fill[1][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[1]+=1

        #Avanza hacia el norte
        elif (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]-1][ubicacion[1]] and flood_fill[2][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[0]-=1

        #Avanza hacia el sur 
        elif (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]+1][ubicacion[1]] and flood_fill[4][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[0]+=1

    #Esquina superior 
    elif ubicacion[0]-1 == -1:
        #avanza hacie el este
        if (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]+1] and flood_fill[1][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[1]+=1

        #Avanza hacia el sur 
        elif (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]+1][ubicacion[1]] and flood_fill[4][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[0]+=1

    #Esquina inferior 
    elif ubicacion[0]+1 == 5:
        #avanza hacia el este 
        if (flood_fill[0][ubicacion[0]][ubicacion[1]+1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]+1] and flood_fill[1][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[1]+=1

        #Avanza hacia el norte
        elif (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]+1] or flood_fill[1][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]-1][ubicacion[1]] and flood_fill[2][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[0]-=1

#Columna derecha 
elif ubicacion[1]+1 == 5:
    #fuera de esquinas
    if ubicacion[0]-1 >= 0 and ubicacion[0]+1 <= 4:
        print("hola1")
        #Avanza hacia el norte
        if (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]-1][ubicacion[1]] and flood_fill[2][ubicacion[0]][ubicacion[1]] != 1:
            print("hola")
            ubicacion[0]-=1
            print(ubicacion[0])
        
        #Avanza hacia el oeste 
        elif (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]-1] and flood_fill[3][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[1]-=1

        #Avanza hacia el sur
        elif (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]+1][ubicacion[1]] and flood_fill[4][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[0]+=1
    
    #esquina superior 
    if ubicacion[0]-1 == -1:
        #Avanza hacia el oeste
        if (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]+1][ubicacion[1]] or flood_fill[4][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]-1] and flood_fill[3][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[1]-=1
        #Avanza hacia el sur
        elif (flood_fill[0][ubicacion[0]+1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]+1][ubicacion[1]] and flood_fill[4][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[0]+=1
    
    #Esquina inferior 
    if ubicacion[0]+1 == 5:
        #avanza hacia el oeste 
        if (flood_fill[0][ubicacion[0]][ubicacion[1]-1] < flood_fill[0][ubicacion[0]-1][ubicacion[1]] or flood_fill[2][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]][ubicacion[1]-1] and flood_fill[3][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[1]-=1

        #Avanza hacia el norte 
        elif (flood_fill[0][ubicacion[0]-1][ubicacion[1]] < flood_fill[0][ubicacion[0]][ubicacion[1]-1] or flood_fill[3][ubicacion[0]][ubicacion[1]] == 1) and flood_fill[0][ubicacion[0]][ubicacion[1]] > flood_fill[0][ubicacion[0]-1][ubicacion[1]] and flood_fill[2][ubicacion[0]][ubicacion[1]] != 1:
            ubicacion[0]-=1
print(flood_fill[0][ubicacion[0]][ubicacion[1]])
print(ubicacion[0]-1 >= 0 and ubicacion[0]+1 <= 4)
    
#print(flood_fill[0])
#print(flood_fill[1:])

False
3.0
True


In [57]:

flood_fill = np.zeros((5,5,5))
with open('archivos_csv/posiciones.csv','r') as csv_file:
    flood_fill[0] = np.loadtxt(csv_file,delimiter=";")
    print(flood_fill[0])
aux=np.array([0,1])
print(True ^ True)


[[ 6.  5.  4.  5.  4.]
 [ 7.  6.  3.  2.  3.]
 [ 8.  9.  0.  1.  2.]
 [ 9.  8.  9. 10.  3.]
 [10.  7.  6.  5.  4.]]
False
